### ISSUE TITLE
forced currency in $

### ISSUE THREAD

**Issue by JJDai54** [XoopsModules25x/adslight#13]
fichier Utility.php
fonction : public static **function getMoneyFormat($format, $number)**
ligne 649
        setlocale(LC_ALL, 'en_US');
        //   setlocale(LC_ALL, 'fr_FR');

la devise est forcée en "$" quelque soit la devise choisie
pourquoi ne pas utiliser l'option "adslight_currency_symbol" de "xoops_version.php" ?
------------------
the currency is forced in "$" whatever the chosen currency
why not use the "adslight_currency_symbol" option of "xoops_version.php"?

**Comment by mambax7** [comment]
Could you test it and submit a Pull Request? 
Thanks!

**Comment by mambax7** [comment]
I've made some changes which are not the cleanest, and probably not what you wanted, but it seems it's working with US$. 
But I'm curious if it works in French/Euro environment? Please check it out and let me know. 
This module needs to be rewritten because there is too much different code mixed in, and too many different approaches. We need to standardize it on the Admin side, so its behavior is more consistent with other modules.
Maybe it's time for version 3.0? :)

**Comment by mambax7** [comment]
I just tested it with different languages set through xLanguage, and I see that the currency doesn't work properly, so I'll have to do some more testing
I'll keep you posted...

**Comment by mambax7** [comment]
With the new function it seems to be working OK, so I'm closing it...
